// CPython set iteration order emulation vs ground truth generated by CPython 3.12
// (tests/goldens/pyset-cases.json: random int keys; comprehension order and union order).
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { PySet } from '../../src/_pyset.js';

interface Case { a: number[]; b: number[]; set_a: number[]; set_b: number[]; union: number[]; set_list_a: number[] }
const cases = JSON.parse(readFileSync(resolve(import.meta.dirname, '../goldens/pyset-cases.json'), 'utf8')) as Case[];

describe('PySet reproduces CPython 3.12 set iteration order for int keys', () => {
  it('comprehension order, set(list) order and union order', () => {
    let checked = 0;
    for (const c of cases) {
      const sa = new PySet(c.a);
      const sb = new PySet(c.b);
      expect(sa.toArray()).toEqual(c.set_a);
      expect(sb.toArray()).toEqual(c.set_b);
      expect(new PySet(c.a).toArray()).toEqual(c.set_list_a);
      expect(sa.union(sb).toArray()).toEqual(c.union);
      checked += 1;
    }
    console.log(`pyset: ${checked} cases`);
  });
});
