// Turn the write-once model artifact into the runtime asset the package bundles eagerly:
//   models/<ship model>.json.gz  →  src/en/data/model.en.ts (generated, gitignored); SRC below is the
//   single source of truth for which model ships (training/ship-model.sh rewrites it; dump-parsed.py reads it)
// Uncompressed on purpose: Hermes has no zlib (docs/PORTING.md §3.9). Run: pnpm model
import { readFileSync, mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { createHash } from 'node:crypto';

const SRC = new URL('../models/brill-porter-full.json.gz', import.meta.url);
const OUT_DIR = new URL('../src/en/data/', import.meta.url);
const OUT = new URL('model.en.ts', OUT_DIR);

const gz = readFileSync(SRC);
const sha = createHash('sha256').update(gz).digest('hex');
const json = gunzipSync(gz).toString('utf8');
const srcRel = decodeURIComponent(SRC.pathname).split('/').slice(-2).join('/');
const marker = `// sha256(${srcRel}) = ${sha}`;
if (existsSync(OUT) && readFileSync(OUT, 'utf8').includes(marker)) {
  console.log('src/en/data/model.en.ts up to date');
} else {
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(
    OUT,
    `// GENERATED by training/extract-model.mjs — do not edit. Provenance: docs/MODELS.md.\n${marker}\n` +
      `import type { CRFModelJson } from '../../inference.js';\nconst model: CRFModelJson = ${json};\nexport default model;\n`,
  );
  console.log(`wrote src/en/data/model.en.ts (${(json.length / 1e6).toFixed(2)} MB raw JSON)`);
}
