// Turn the vendored Brill tagger data into the runtime asset the package bundles eagerly:
//   models/natural/lexicon_from_posjs.json.gz + tr_from_posjs.txt  →  src/en/data/brill.en.ts
// (generated, gitignored; provenance in models/natural/README.md). Run: pnpm model
//
// Only what the tagger reads is kept: natural's `Lexicon.tagWord` returns the entry's category
// list and `BrillPOSTagger.tagWithLexicon` uses its first element, so the asset stores the first
// category of every word, grouped by category — 72 groups of '\n'-joined words (no word contains
// whitespace or a control character; the generator checks) instead of 92,662 JSON arrays:
// ~1.2 MB of module text instead of 4.0 MB. The one entry with an empty word and no categories
// is dropped (natural would tag an empty token `undefined`; the tokenizer never yields one).
import { readFileSync, mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { createHash } from 'node:crypto';

const LEXICON_GZ = new URL('../models/natural/lexicon_from_posjs.json.gz', import.meta.url);
const RULES = new URL('../models/natural/tr_from_posjs.txt', import.meta.url);
const OUT_DIR = new URL('../src/en/data/', import.meta.url);
const OUT = new URL('brill.en.ts', OUT_DIR);
const SELF = new URL(import.meta.url);

const sha = (buf) => createHash('sha256').update(buf).digest('hex');
const rel = (u) => decodeURIComponent(u.pathname).split('/').slice(-2).join('/');

const lexiconGz = readFileSync(LEXICON_GZ);
const rulesText = readFileSync(RULES, 'utf8');
const marker = `// sha256(${rel(LEXICON_GZ)}) = ${sha(lexiconGz)}; sha256(${rel(RULES)}) = ${sha(rulesText)}; sha256(${rel(SELF)}) = ${sha(readFileSync(SELF))}`;
if (existsSync(OUT) && readFileSync(OUT, 'utf8').includes(marker)) {
  console.log('src/en/data/brill.en.ts up to date');
  process.exit(0);
}

const lexicon = JSON.parse(gunzipSync(lexiconGz).toString('utf8'));
if (Object.getPrototypeOf(lexicon) !== Object.prototype) throw new Error('lexicon: unexpected JSON shape');
const groups = new Map(); // first category → words, in lexicon order
let entries = 0;
let dropped = 0;
for (const [word, categories] of Object.entries(lexicon)) {
  entries += 1;
  if (!Array.isArray(categories) || categories.some((c) => typeof c !== 'string')) throw new Error(`lexicon: bad entry ${JSON.stringify(word)}`);
  if (categories.length === 0) {
    if (word !== '') throw new Error(`lexicon: ${JSON.stringify(word)} has no categories`);
    dropped += 1;
    continue;
  }
  if (word === '' || /[\s\p{Cc}]/u.test(word)) throw new Error(`lexicon: word ${JSON.stringify(word)} cannot be '\\n'-joined`);
  const tag = categories[0];
  if (tag === '' || /[\s\p{Cc}]/u.test(tag)) throw new Error(`lexicon: bad category ${JSON.stringify(tag)}`);
  let words = groups.get(tag);
  if (words === undefined) groups.set(tag, (words = []));
  words.push(word);
}
if (entries !== 92662 || dropped !== 1) throw new Error(`lexicon: expected 92,662 entries with 1 empty, got ${entries} / ${dropped}`);

const rules = rulesText.split(/\r?\n/).filter((line) => line.trim() !== '');
if (rules.length !== 18) throw new Error(`rules: expected 18, got ${rules.length}`);

const tags = [...groups.keys()];
const words = tags.map((t) => groups.get(t).join('\n'));
const text =
  `// GENERATED by training/extract-brill.mjs — do not edit. Provenance: models/natural/README.md.\n${marker}\n` +
  `/** Lexical categories, one per group of BRILL_WORDS (${tags.length} groups, ${entries - dropped} words). */\n` +
  `export const BRILL_TAGS: readonly string[] = ${JSON.stringify(tags)};\n` +
  `/** The words whose first category is BRILL_TAGS[i], '\\n'-separated, in lexicon order. */\n` +
  `export const BRILL_WORDS: readonly string[] = [\n${words.map((w) => `  ${JSON.stringify(w)},\n`).join('')}];\n` +
  `/** natural's English transformation rules, in file order: "FROM TO PREDICATE [PARAMETER]". */\n` +
  `export const BRILL_RULES: readonly string[] = ${JSON.stringify(rules, null, 2)};\n`;
mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT, text);
console.log(`wrote src/en/data/brill.en.ts (${(text.length / 1e6).toFixed(2)} MB, ${tags.length} categories, ${entries - dropped} words, ${rules.length} rules)`);
