"""Generate src/en/_constants.ts and src/en/_htmlEntities.ts from upstream (at the pin) and
Python's stdlib, so the tables are transcribed mechanically, never by hand (CLAUDE.md §3).

Run from the repo root: ip-repo/venv/bin/python training/gen-constants.py
Sets are emitted as sorted arrays (Python set order is hash-randomised; every consumer in
the port treats them as membership sets). Dicts keep insertion order. Canonical JSON.
"""
import html, html.entities, json, sys, subprocess
sys.path.insert(0, 'ip-repo')
from ingredient_parser.en import _constants as C

pin = subprocess.run(['git', '-C', 'ip-repo', 'rev-parse', 'HEAD'], capture_output=True, text=True).stdout.strip()
J = lambda o: json.dumps(o, separators=(",", ":"), ensure_ascii=False)
def ts_list_of_sets(name, val):
    return f"export const {name}: ReadonlySet<string>[] = {J([sorted(s) for s in val])}.map((s) => new Set(s));\n"
def ts_set(name, val):
    return f"export const {name}: ReadonlySet<string> = new Set({J(sorted(val))});\n"
def ts_list(name, val, t="string"):
    return f"export const {name}: readonly {t}[] = {J(val)};\n"
def ts_dict(name, val):
    return f"export const {name}: Readonly<Record<string, string>> = {J(val)};\n"

out = [f"""// GENERATED by training/gen-constants.py from ingredient_parser/en/_constants.py @ {pin}.
// Do not edit by hand — regenerate. Sets are sorted arrays wrapped in Set; dicts keep upstream order.
// Mirrors upstream names verbatim (CLAUDE.md §5).
/* eslint-disable */
import {{ PY_B, pyReIgnoreCase }} from '../_py.js';
"""]
out.append("/** Plural → singular units, including the capitalised variants upstream generates at import. */\n")
out.append(ts_dict("UNITS", C.UNITS))
out.append("/** Every key and value of UNITS. */\n")
out.append(ts_set("FLATTENED_UNITS_LIST", C.FLATTENED_UNITS_LIST))
out.append(ts_list("AMBIGUOUS_UNITS", C.AMBIGUOUS_UNITS))
out.append(ts_list("SIZES", C.SIZES))
out.append(ts_dict("STRING_NUMBERS", C.STRING_NUMBERS))
out.append(ts_dict("UNICODE_FRACTIONS", C.UNICODE_FRACTIONS))
out.append(ts_set("STOP_WORDS", C.STOP_WORDS))
out.append(ts_list("APPROXIMATE_PREFIXES", C.APPROXIMATE_PREFIXES))
out.append(f"export const APPROXIMATE_SUFFIXES: readonly (readonly string[])[] = {J(C.APPROXIMATE_SUFFIXES)};\n")
out.append(ts_list("SINGULAR_TOKENS", C.SINGULAR_TOKENS))
out.append(f"export const PREPARED_INGREDIENT_TOKENS: readonly (readonly string[])[] = {J(C.PREPARED_INGREDIENT_TOKENS)};\n")
out.append(ts_list_of_sets("UNIT_SYNONYMS", C.UNIT_SYNONYMS))
out.append(ts_set("LENGTH_UNITS", C.LENGTH_UNITS))
out.append(ts_set("DIMENSIONS", C.DIMENSIONS))
out.append(ts_set("INDEFINITE_QUANTIFIERS", C.INDEFINITE_QUANTIFIERS))
import unicodedata as _ud
_extra = sorted(cp for cp in range(0x110000) if (ch := chr(cp)).isnumeric() and _ud.category(ch)[0] != "N")
out.append("/** Code points where str.isnumeric() is True but the Unicode category is not N (CJK numerals etc.); with \\\\p{N} this is Python's isnumeric/isdigit/isdecimal union. */\n")
out.append(f"export const PY_ISNUMERIC_EXTRA: ReadonlySet<number> = new Set({J(_extra)});\n")
_digit_extra = sorted(cp for cp in range(0x110000) if (ch := chr(cp)).isdigit() and _ud.category(ch) != "Nd")
out.append("/** Code points where str.isdigit() is True but the category is not Nd (superscripts, circled digits …); with \\\\p{Nd} this is Python's isdigit. */\n")
out.append(f"export const PY_ISDIGIT_EXTRA: ReadonlySet<number> = new Set({J(_digit_extra)});\n")
out.append('''/** Precompiled `\\b(<string number>)\\b` (case-insensitive) → numeral, in STRING_NUMBERS order. */
export const STRING_NUMBERS_REGEXES: Readonly<Record<string, readonly [RegExp, string]>> = Object.fromEntries(
  Object.entries(STRING_NUMBERS).map(([s, n]) => [s, [new RegExp(pyReIgnoreCase(`${PY_B}(${s})${PY_B}`), 'giu'), n] as const]),
);
''')
# Sanity: every upstream public constant is covered
public = {n for n in dir(C) if n.isupper()}
covered = {"UNITS","FLATTENED_UNITS_LIST","AMBIGUOUS_UNITS","SIZES","STRING_NUMBERS","STRING_NUMBERS_REGEXES","UNICODE_FRACTIONS","STOP_WORDS","APPROXIMATE_PREFIXES","APPROXIMATE_SUFFIXES","SINGULAR_TOKENS","PREPARED_INGREDIENT_TOKENS","UNIT_SYNONYMS","LENGTH_UNITS","DIMENSIONS","INDEFINITE_QUANTIFIERS"}
missing = public - covered
assert not missing, f"uncovered constants: {missing}"
open('src/en/_constants.ts', 'w').write("".join(out))
print("src/en/_constants.ts:", len("".join(out)), "bytes; STRING_NUMBERS_REGEXES is built in TS from STRING_NUMBERS")

ent = [f"""// GENERATED by training/gen-constants.py from Python {sys.version.split()[0]} stdlib html.entities / html.
// Do not edit by hand — regenerate. Backs the port of html.unescape() (used by
// PreProcessor._replace_html_fractions). Canonical JSON, raw unicode.
/* eslint-disable */
"""]
ent.append(f"/** html.entities.html5: entity name (with or without trailing ';') → replacement text. */\nexport const HTML5_ENTITIES: Readonly<Record<string, string>> = {J(html.entities.html5)};\n")
ent.append(f"/** html._invalid_charrefs: numeric char refs that browsers remap (e.g. 0x80 → '€'). Keys are code points. */\nexport const INVALID_CHARREFS: Readonly<Record<string, string>> = {J({str(k): v for k, v in html._invalid_charrefs.items()})};\n")
ent.append(f"/** html._invalid_codepoints: numeric char refs that decode to nothing. */\nexport const INVALID_CODEPOINTS: ReadonlySet<number> = new Set({J(sorted(html._invalid_codepoints))});\n")
open('src/en/_htmlEntities.ts', 'w').write("".join(ent))
print("src/en/_htmlEntities.ts:", len("".join(ent)), "bytes")
