"""Generate src/en/_pintRegistry.ts: the pint unit registry as upstream constructs it
(pint.UnitRegistry() + ingredient_parser/pint_extensions.txt), dumped from a FRESH registry
so no runtime-added prefixed names leak in. Backs the pint subset in src/_pint.ts.

Run from the repo root: ip-repo/venv/bin/python training/gen-pint.py
"""
import json, math, sys
from pathlib import Path
import pint

ext = Path('ip-repo/ingredient_parser/pint_extensions.txt')
ureg = pint.UnitRegistry()
ureg.load_definitions(ext)

J = lambda o: json.dumps(o, separators=(",", ":"), ensure_ascii=False)

def num(v):
    # Scales are Python floats (non_int_type=float); emit repr so they round-trip exactly.
    if isinstance(v, float):
        if math.isnan(v): return "NaN"
        if math.isinf(v): return "Infinity" if v > 0 else "-Infinity"
        return repr(v)
    return repr(v)

units_index = {}
defs = {}
for key, d in ureg._units.items():
    units_index[key] = d.name
    if d.name not in defs:
        conv = d.converter
        defs[d.name] = {
            "is_base": bool(d.is_base),
            "scale": num(getattr(conv, "scale", 1)),
            "offset": num(getattr(conv, "offset", 0)),
            "is_multiplicative": bool(conv.is_multiplicative),
            "is_logarithmic": bool(getattr(conv, "is_logarithmic", False)),
            "logbase": num(getattr(conv, "logbase", 0)),
            "logfactor": num(getattr(conv, "logfactor", 0)),
            # Exponents keep Python's int/float distinction (repr strings; the TS side parses them):
            # pint formats int exponents in full and float ones with format(x, "n").
            "reference": {k: repr(v) for k, v in d.reference.items()} if d.reference is not None else None,
        }
prefix_keys = list(ureg._prefixes.keys())
prefixes = {k: {"name": p.name, "scale": num(p.converter.scale)} for k, p in ureg._prefixes.items()}
suffixes = {k: v for k, v in ureg._suffixes.items()}
dims = {k: ({kk: repr(vv) for kk, vv in d.reference.items()} if getattr(d, "reference", None) is not None else None) for k, d in ureg._dimensions.items()}
# Base units of the default system ("mks"): root unit -> UnitsContainer (Quantity.to_base_units).
mks_base = {k: {kk: repr(vv) for kk, vv in v.items()} for k, v in ureg.get_system(ureg._default_system_name).base_units.items()}

# Python codec registry, for the PEP 263 coding cookie that pint's tokenizer (Python `tokenize`) honours.
import codecs, encodings, encodings.aliases, pkgutil
codec_modules = {}
for m in pkgutil.iter_modules(encodings.__path__):
    if m.name in ("aliases",):
        continue
    try:
        codecs.lookup(m.name)
    except LookupError:
        continue  # e.g. mbcs/oem: not importable on this platform
    try:
        probe = b"cup #\xc3\xa9".decode(m.name, "replace")
    except Exception as e:  # noqa: BLE001 - bytes->bytes codecs raise LookupError, idna/undefined UnicodeError
        codec_modules[m.name] = "raise:" + type(e).__name__
        continue
    if m.name == "utf_8":
        codec_modules[m.name] = "utf8"
    elif m.name == "latin_1":
        codec_modules[m.name] = "latin1"
    elif m.name == "ascii":
        codec_modules[m.name] = "ascii"
    elif probe.startswith("cup #"):
        codec_modules[m.name] = "ascii-compatible"
    else:
        codec_modules[m.name] = "incompatible"
codec_aliases = dict(encodings.aliases.aliases)

# string_preprocessor substitutions (pint.util._subs_re_list) as (pattern, replacement) pairs
import pint.util as U
subs = [(a.pattern, b) for a, b in U._subs_re]
pretty_exp = U._pretty_exp_re.pattern
pretty_table = {chr(k): chr(v) for k, v in U._pretty_table.items()}

def ts_num_record(name, rec, doc):
    # values are numeric reprs → emit as JS number literals via a small transform
    items = []
    for k, v in rec.items():
        items.append(J(k) + ":" + json.dumps(v))
    return f"/** {doc} */\nexport const {name} = {{{','.join(items)}}} as const;\n"

def defs_ts():
    parts = []
    for name, d in defs.items():
        ref = "null" if d["reference"] is None else J(d["reference"])
        parts.append(f'{J(name)}:{{is_base:{str(d["is_base"]).lower()},scale:{d["scale"]},offset:{d["offset"]},is_multiplicative:{str(d["is_multiplicative"]).lower()},is_logarithmic:{str(d["is_logarithmic"]).lower()},logbase:{d["logbase"]},logfactor:{d["logfactor"]},reference:{ref}}}')
    return "{" + ",".join(parts) + "}"

def prefixes_ts():
    return "{" + ",".join(f'{J(k)}:{{name:{J(v["name"])},scale:{v["scale"]}}}' for k, v in prefixes.items()) + "}"

out = f"""// GENERATED by training/gen-pint.py from pint {pint.__version__} default registry +
// ingredient_parser/pint_extensions.txt (upstream pin). Do not edit by hand — regenerate.
/* eslint-disable */
export const PINT_VERSION = {J(pint.__version__)};

export interface PintUnitDef {{
  is_base: boolean;
  /** Multiplicative scale to the reference (Python float repr, exact). */
  scale: number;
  offset: number;
  is_multiplicative: boolean;
  /** LogarithmicConverter units (dB, octave, neper…): logbase/logfactor of pint's definition. */
  is_logarithmic: boolean;
  logbase: number;
  logfactor: number;
  /**
   * Reference units (or base dimensions for base units) → exponent, as Python `repr` so the
   * int/float distinction survives ("2" is an int, "2.0"/"0.5" are floats).
   */
  reference: Readonly<Record<string, string>> | null;
}}

/** Every registered name, symbol and alias → canonical unit name ({len(units_index)} keys). */
export const UNITS_INDEX: Readonly<Record<string, string>> = {J(units_index)};

/** Canonical unit name → definition ({len(defs)} units). */
export const UNIT_DEFS: Readonly<Record<string, PintUnitDef>> = {defs_ts()};

/** Prefix keys in registry (iteration) order — parse_unit_name walks them in this order. */
export const PREFIX_KEYS: readonly string[] = {J(prefix_keys)};
/** Prefix key (name, symbol or alias) → canonical prefix name and scale. */
export const PREFIXES: Readonly<Record<string, {{ name: string; scale: number }}>> = {prefixes_ts()};
/** Suffix key → suffix name (both map to '' in pint). */
export const SUFFIXES: Readonly<Record<string, string>> = {J(suffixes)};
/** Dimension name → reference dimensions as Python reprs (base dimensions have null). */
export const DIMENSIONS: Readonly<Record<string, Readonly<Record<string, string>> | null>> = {J(dims)};
/** Base units of the default system ({J(ureg._default_system_name)}): root unit → container (exponents as Python reprs). */
export const MKS_BASE_UNITS: Readonly<Record<string, Readonly<Record<string, string>>>> = {J(mks_base)};
/**
 * Python codec registry on the reference machine: encodings-package module name → how the port can
 * decode with it ("utf8", "latin1", "ascii", "ascii-compatible", "incompatible", "raise:<Class>").
 */
export const CODEC_MODULES: Readonly<Record<string, string>> = {J(codec_modules)};
/** `encodings.aliases.aliases`: normalised alias → module name. */
export const CODEC_ALIASES: Readonly<Record<string, string>> = {J(codec_aliases)};

/** pint.util string_preprocessor substitutions, in order (Python regex source, replacement). */
export const SUBS_RE: readonly (readonly [string, string])[] = {J(subs)};
export const PRETTY_EXP_RE = {J(pretty_exp)};
export const PRETTY_TABLE: Readonly<Record<string, string>> = {J(pretty_table)};
"""
Path('src/en/_pintRegistry.ts').write_text(out)
print("units keys", len(units_index), "| defs", len(defs), "| prefixes", len(prefix_keys), "| dims", len(dims), "| bytes", len(out))
# sanity prints
print("kilogram in fresh _units:", "kilogram" in ureg._units, "| cup:", defs["cup"], "| liter:", defs["liter"], "| gram:", defs["gram"])
print("subs:", subs)
print("pretty_exp:", pretty_exp, "| pretty_table:", pretty_table)
