"""Generate the foundation-foods runtime assets (gitignored, lazy-loaded) from upstream's data
files at the pin:
  ingredient_parser/en/data/ingredient_embeddings.35d.glove.txt.gz → src/en/data/glove.en.ts
  ingredient_parser/en/data/fdc_ingredients.csv.gz                  → src/en/data/fdc.en.ts
GloVe values are parsed exactly as upstream (`float(v)` then float32) and shipped as base64 of
little-endian float32; the FDC CSV is parsed with Python's csv module so quoting matches.
Run from the repo root: ip-repo/venv/bin/python training/gen-ff-assets.py
"""
import base64, csv, gzip, json, struct, subprocess
from pathlib import Path
import numpy as np

pin = subprocess.run(['git', '-C', 'ip-repo', 'rev-parse', 'HEAD'], capture_output=True, text=True).stdout.strip()
data = Path('ip-repo/ingredient_parser/en/data')
out_dir = Path('src/en/data'); out_dir.mkdir(parents=True, exist_ok=True)
J = lambda o: json.dumps(o, separators=(",", ":"), ensure_ascii=False)

# ---- GloVe ----
vocab = []
vecs = []
with gzip.open(data / 'ingredient_embeddings.35d.glove.txt.gz', 'rt') as f:
    header = f.readline().rstrip()
    vocab_size, dim = map(int, header.split())
    for line in f:
        parts = line.rstrip().split()
        vocab.append(parts[0])
        vecs.append(np.array([float(v) for v in parts[1:]], dtype=np.float32))
# The header understates the row count by one (19850 vs 19851); upstream keeps every line and
# only stores the header value as `vocab_size`. Mirror that.
assert all(len(v) == dim for v in vecs)
flat = np.concatenate(vecs).astype('<f4')
b64 = base64.b64encode(flat.tobytes()).decode('ascii')
(out_dir / 'glove.en.ts').write_text(
    f"// GENERATED by training/gen-ff-assets.py from ingredient_embeddings.35d.glove.txt.gz @ {pin}. Do not edit.\n"
    f"/** Header value (upstream `vocab_size`); VOCAB.length is the real row count. */\nexport const VOCAB_SIZE = {vocab_size};\nexport const DIMENSION = {dim};\n"
    f"export const VOCAB: readonly string[] = {J(vocab)};\n"
    f"/** {len(vocab)} x {dim} float32, little-endian, row-major, base64. */\nexport const VECTORS_B64 = {J(b64)};\n")
print(f"glove.en.ts: {len(vocab)} rows (header {vocab_size}) x {dim}, {len(b64)/1e6:.2f} MB base64")

# ---- FDC ----
rows = []
with gzip.open(data / 'fdc_ingredients.csv.gz', 'rt') as f:
    for row in csv.DictReader(f):
        rows.append({"fdc_id": int(row["fdc_id"]), "data_type": row["data_type"], "description": row["description"], "category": row["category"]})
(out_dir / 'fdc.en.ts').write_text(
    f"// GENERATED by training/gen-ff-assets.py from fdc_ingredients.csv.gz @ {pin}. Do not edit.\n"
    f"export interface FDCRow {{ fdc_id: number; data_type: string; description: string; category: string }}\n"
    f"export const FDC_ROWS: readonly FDCRow[] = {J(rows)};\n")
print(f"fdc.en.ts: {len(rows)} rows")
