// Verbatim conversion of ip-repo/tests/preprocess/test_preprocess.py @ ffd6ae3 (32 tests: 2 + 29 parametrized + 1).
// Do not edit expectations here — they are upstream's. See tests/upstream/README.md.
import { describe, it, expect } from "vitest";

import { PreProcessor } from "../../../src/en/index.js";
import type { FeatureDict } from "../../../src/en/index.js";

describe("TestPreProcessor__builtins__", () => {
  it("test__str__", () => {
    // Test PreProcessor __str__
    const p = new PreProcessor("1/2 cup chicken broth", { custom_units: {} });
    // CONVERSION NOTE: Python triple-quoted string with `\t` escapes; the template literal
    // below yields the byte-identical string (tabs via \t escapes, real newlines).
    const truth = `Pre-processed recipe ingredient sentence
\t  Input: 1/2 cup chicken broth
\tCleaned: #1$2 cup chicken broth
\t Tokens: ['#1$2', 'cup', 'chicken', 'broth']`;
    expect(p.toString()).toBe(truth);
  });

  it("test__repr__", () => {
    // Test PreProessor __repr__
    const p = new PreProcessor("1/2 cup chicken broth", { custom_units: {} });
    expect(p.repr()).toBe('PreProcessor("1/2 cup chicken broth")');
  });
});

// Return a list of tuples of input sentences and their normalised form.
// Many of these examples are based on the examples in docstrings for the
// PreProcessor functions.
function normalise_test_cases(): [string, string][] {
  return [
    ["&frac12; cup warm water (105°F)", "#1$2 cup warm water (105°F)"],
    ["3 1/2 chilis anchos", "3#1$2 chilis anchos"],
    ["six eggs", "six eggs"],
    ["thumbnail-size piece ginger", "thumbnail-size piece ginger"],
    [
      "2 cups flour – white or self-raising",
      "2 cups flour - white or self-raising",
    ],
    ["3–4 sirloin steaks", "3-4 sirloin steaks"],
    ["three large onions", "three large onions"],
    ["twelve bonbons", "twelve bonbons"],
    ["1&frac34; cups tomato ketchup", "1#3$4 cups tomato ketchup"],
    ["1/2 cup icing sugar", "#1$2 cup icing sugar"],
    ["2 3/4 pound chickpeas", "2#3$4 pound chickpeas"],
    ["1 and 1/2 tsp fine grain sea salt", "1#1$2 tsp fine grain sea salt"],
    ["1 and 1/4 cups dark chocolate morsels", "1#1$4 cups dark chocolate morsels"],
    ["½ cup icing sugar", "#1$2 cup icing sugar"],
    ["3⅓ cups warm water", "3#1$3 cups warm water"],
    ["¼-½ teaspoon", "#1$4-#1$2 teaspoon"],
    ["100g green beans", "100 g green beans"],
    ["2-pound red peppers, sliced", "2 pound red peppers, sliced"],
    ["2lb1oz cherry tomatoes", "2 lb 1 oz cherry tomatoes"],
    ["2lb-1oz cherry tomatoes", "2 lb - 1 oz cherry tomatoes"],
    ["1 tsp. garlic powder", "1 tsp garlic powder"],
    ["5 oz. chopped tomatoes", "5 oz chopped tomatoes"],
    ["1 to 2 mashed bananas", "1-2 mashed bananas"],
    ["5- or 6- large apples", "5-6- large apples"],
    ["227 g - 283.5 g/8-10 oz duck breast", "227-283.5 g/8-10 oz duck breast"],
    ["400-500 g/14 oz - 17 oz rhubarb", "400-500 g/14-17 oz rhubarb"],
    ["8 x 450 g/1 lb live lobsters", "8x 450 g/1 lb live lobsters"],
    ["4 x 100 g wild salmon fillet", "4x 100 g wild salmon fillet"],
    [
      "½ - ¾ cup heavy cream, plus extra for brushing the tops of the scones",
      "#1$2-#3$4 cup heavy cream, plus extra for brushing the tops of the scones",
    ],
  ];
}

describe("TestPreProcessor_normalise", () => {
  // CONVERSION NOTE: upstream parametrizes a single `testcase` tuple and unpacks it in the
  // body (`input_sentence, normalised = testcase`); vitest's it.each spreads each tuple into
  // the callback arguments, which is the same unpacking.
  it.each(normalise_test_cases())("test_normalise %#", (input_sentence, normalised) => {
    // Test that each example sentence is normalised correctly
    const p = new PreProcessor(input_sentence, { custom_units: {} });
    expect(p.sentence).toBe(normalised);
  });
});

describe("TestPreProcessor_sentence_features", () => {
  it("test", () => {
    const p = new PreProcessor("1/2 cup chicken broth", { custom_units: {} });
    const expected: FeatureDict[] = [
      {
        "bias": "",
        "sentence_length": "4",
        "pos": "CD",
        "stem": "!num",
        "is_capitalised": false,
        "is_unit": false,
        "is_punc": false,
        "is_ambiguous": false,
        "is_in_parens": false,
        "is_after_comma": false,
        "is_after_plus": false,
        "word_shape": "!xxx",
        "is_length_unit": false,
        "is_dimension": false,
        "mip_start": false,
        "mip_end": false,
        "after_sentence_split": false,
        "example_phrase": false,
        "next_stem": "cup",
        "next_pos_ngram": "CD+NN",
        "next_pos": "NN",
        "next_is_capitalised": false,
        "next_is_unit": true,
        "next_is_punc": false,
        "next_is_ambiguous": false,
        "next_is_in_parens": false,
        "next_is_after_comma": false,
        "next_is_after_plus": false,
        "next_word_shape": "xxx",
        "next_is_length_unit": false,
        "next_is_dimension": false,
        "next_mip_start": false,
        "next_mip_end": false,
        "next_after_sentence_split": false,
        "next_example_phrase": false,
        "next2_stem": "chicken",
        "next2_pos_ngram": "CD+NN+NN",
        "next2_pos": "NN",
        "next2_is_capitalised": false,
        "next2_is_unit": false,
        "next2_is_punc": false,
        "next2_is_ambiguous": false,
        "next2_is_in_parens": false,
        "next2_is_after_comma": false,
        "next2_is_after_plus": false,
        "next2_word_shape": "xxxxxxx",
        "next2_is_length_unit": false,
        "next2_is_dimension": false,
        "next2_mip_start": false,
        "next2_mip_end": false,
        "next2_after_sentence_split": false,
        "next2_example_phrase": false,
        "next3_stem": "broth",
        "next3_pos_ngram": "CD+NN+NN+NN",
        "next3_pos": "NN",
        "next3_is_capitalised": false,
        "next3_is_unit": false,
        "next3_is_punc": false,
        "next3_is_ambiguous": false,
        "next3_is_in_parens": false,
        "next3_is_after_comma": false,
        "next3_is_after_plus": false,
        "next3_word_shape": "xxxxx",
        "next3_is_length_unit": false,
        "next3_is_dimension": false,
        "next3_mip_start": false,
        "next3_mip_end": false,
        "next3_after_sentence_split": false,
        "next3_example_phrase": false,
      },
      {
        "bias": "",
        "sentence_length": "4",
        "pos": "NN",
        "stem": "cup",
        "is_capitalised": false,
        "is_unit": true,
        "is_punc": false,
        "is_ambiguous": false,
        "is_in_parens": false,
        "is_after_comma": false,
        "is_after_plus": false,
        "word_shape": "xxx",
        "is_length_unit": false,
        "is_dimension": false,
        "mip_start": false,
        "mip_end": false,
        "after_sentence_split": false,
        "example_phrase": false,
        "prev_stem": "!num",
        "prev_pos_ngram": "CD+NN",
        "prev_pos": "CD",
        "prev_is_capitalised": false,
        "prev_is_unit": false,
        "prev_is_punc": false,
        "prev_is_ambiguous": false,
        "prev_is_in_parens": false,
        "prev_is_after_comma": false,
        "prev_is_after_plus": false,
        "prev_word_shape": "!xxx",
        "prev_is_length_unit": false,
        "prev_is_dimension": false,
        "prev_mip_start": false,
        "prev_mip_end": false,
        "prev_after_sentence_split": false,
        "prev_example_phrase": false,
        "next_stem": "chicken",
        "next_pos_ngram": "NN+NN",
        "next_pos": "NN",
        "next_is_capitalised": false,
        "next_is_unit": false,
        "next_is_punc": false,
        "next_is_ambiguous": false,
        "next_is_in_parens": false,
        "next_is_after_comma": false,
        "next_is_after_plus": false,
        "next_word_shape": "xxxxxxx",
        "next_is_length_unit": false,
        "next_is_dimension": false,
        "next_mip_start": false,
        "next_mip_end": false,
        "next_after_sentence_split": false,
        "next_example_phrase": false,
        "next2_stem": "broth",
        "next2_pos_ngram": "NN+NN+NN",
        "next2_pos": "NN",
        "next2_is_capitalised": false,
        "next2_is_unit": false,
        "next2_is_punc": false,
        "next2_is_ambiguous": false,
        "next2_is_in_parens": false,
        "next2_is_after_comma": false,
        "next2_is_after_plus": false,
        "next2_word_shape": "xxxxx",
        "next2_is_length_unit": false,
        "next2_is_dimension": false,
        "next2_mip_start": false,
        "next2_mip_end": false,
        "next2_after_sentence_split": false,
        "next2_example_phrase": false,
      },
      {
        "bias": "",
        "sentence_length": "4",
        "pos": "NN",
        "stem": "chicken",
        "is_capitalised": false,
        "is_unit": false,
        "is_punc": false,
        "is_ambiguous": false,
        "is_in_parens": false,
        "is_after_comma": false,
        "is_after_plus": false,
        "word_shape": "xxxxxxx",
        "is_length_unit": false,
        "is_dimension": false,
        "prefix_3": "chi",
        "suffix_3": "ken",
        "prefix_4": "chic",
        "suffix_4": "cken",
        "prefix_5": "chick",
        "suffix_5": "icken",
        "mip_start": false,
        "mip_end": false,
        "after_sentence_split": false,
        "example_phrase": false,
        "prev_stem": "cup",
        "prev_pos_ngram": "NN+NN",
        "prev_pos": "NN",
        "prev_is_capitalised": false,
        "prev_is_unit": true,
        "prev_is_punc": false,
        "prev_is_ambiguous": false,
        "prev_is_in_parens": false,
        "prev_is_after_comma": false,
        "prev_is_after_plus": false,
        "prev_word_shape": "xxx",
        "prev_is_length_unit": false,
        "prev_is_dimension": false,
        "prev_mip_start": false,
        "prev_mip_end": false,
        "prev_after_sentence_split": false,
        "prev_example_phrase": false,
        "prev2_stem": "!num",
        "prev2_pos_ngram": "CD+NN+NN",
        "prev2_pos": "CD",
        "prev2_is_capitalised": false,
        "prev2_is_unit": false,
        "prev2_is_punc": false,
        "prev2_is_ambiguous": false,
        "prev2_is_in_parens": false,
        "prev2_is_after_comma": false,
        "prev2_is_after_plus": false,
        "prev2_word_shape": "!xxx",
        "prev2_is_length_unit": false,
        "prev2_is_dimension": false,
        "prev2_mip_start": false,
        "prev2_mip_end": false,
        "prev2_after_sentence_split": false,
        "prev2_example_phrase": false,
        "next_stem": "broth",
        "next_pos_ngram": "NN+NN",
        "next_pos": "NN",
        "next_is_capitalised": false,
        "next_is_unit": false,
        "next_is_punc": false,
        "next_is_ambiguous": false,
        "next_is_in_parens": false,
        "next_is_after_comma": false,
        "next_is_after_plus": false,
        "next_word_shape": "xxxxx",
        "next_is_length_unit": false,
        "next_is_dimension": false,
        "next_mip_start": false,
        "next_mip_end": false,
        "next_after_sentence_split": false,
        "next_example_phrase": false,
      },
      {
        "bias": "",
        "sentence_length": "4",
        "pos": "NN",
        "stem": "broth",
        "is_capitalised": false,
        "is_unit": false,
        "is_punc": false,
        "is_ambiguous": false,
        "is_in_parens": false,
        "is_after_comma": false,
        "is_after_plus": false,
        "word_shape": "xxxxx",
        "is_length_unit": false,
        "is_dimension": false,
        "prefix_3": "bro",
        "suffix_3": "oth",
        "prefix_4": "brot",
        "suffix_4": "roth",
        "mip_start": false,
        "mip_end": false,
        "after_sentence_split": false,
        "example_phrase": false,
        "prev_stem": "chicken",
        "prev_pos_ngram": "NN+NN",
        "prev_pos": "NN",
        "prev_is_capitalised": false,
        "prev_is_unit": false,
        "prev_is_punc": false,
        "prev_is_ambiguous": false,
        "prev_is_in_parens": false,
        "prev_is_after_comma": false,
        "prev_is_after_plus": false,
        "prev_word_shape": "xxxxxxx",
        "prev_is_length_unit": false,
        "prev_is_dimension": false,
        "prev_mip_start": false,
        "prev_mip_end": false,
        "prev_after_sentence_split": false,
        "prev_example_phrase": false,
        "prev2_stem": "cup",
        "prev2_pos_ngram": "NN+NN+NN",
        "prev2_pos": "NN",
        "prev2_is_capitalised": false,
        "prev2_is_unit": true,
        "prev2_is_punc": false,
        "prev2_is_ambiguous": false,
        "prev2_is_in_parens": false,
        "prev2_is_after_comma": false,
        "prev2_is_after_plus": false,
        "prev2_word_shape": "xxx",
        "prev2_is_length_unit": false,
        "prev2_is_dimension": false,
        "prev2_mip_start": false,
        "prev2_mip_end": false,
        "prev2_after_sentence_split": false,
        "prev2_example_phrase": false,
        "prev3_stem": "!num",
        "prev3_pos_ngram": "CD+NN+NN+NN",
        "prev3_pos": "CD",
        "prev3_is_capitalised": false,
        "prev3_is_unit": false,
        "prev3_is_punc": false,
        "prev3_is_ambiguous": false,
        "prev3_is_in_parens": false,
        "prev3_is_after_comma": false,
        "prev3_is_after_plus": false,
        "prev3_word_shape": "!xxx",
        "prev3_is_length_unit": false,
        "prev3_is_dimension": false,
        "prev3_mip_start": false,
        "prev3_mip_end": false,
        "prev3_after_sentence_split": false,
        "prev3_example_phrase": false,
      },
    ];

    expect(p.sentence_features()).toEqual(expected);
  });
});
